
hiddenimports = [ 'pysam.Pileup'
                , 'pysam.bcftools'
                , 'pysam.calignedsegment'
                , 'pysam.calignmentfile'
                , 'pysam.cbcf'
                , 'pysam.cfaidx'
                , 'pysam.config'
                , 'pysam.csamfile'
                , 'pysam.ctabix'
                , 'pysam.ctabixproxies'
                , 'pysam.cutils'
                , 'pysam.cvcf'
                , 'pysam.include'
                , 'pysam.libchtslib'
                , 'pysam.namedtuple'
                , 'pysam.samtools'
                , 'pysam.utils'
                , 'pysam.version'
                ]
